name: Deploy bebTimer Front to AWS

on:
  push:
    branches:
      - master
      - test-master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BEBTIMER_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.BEBTIMER_EC2_SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/bebTimerFront"

      - name: Install Node.js on EC2
        run: |
          echo "${{ secrets.BEBTIMER_EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.BEBTIMER_EC2_HOST }} << 'EOF'
          
            # Instalacja Node.js na EC2
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          EOF

      - name: ENV creating
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.BEBTIMER_EC2_HOST }} << 'EOF'
            
            # Tworzenie pliku .env
            cd /home/ubuntu/bebTimerFront
            cat <<EOL > .env
            VITE_APP_API_URL=${{ secrets.VITE_APP_API_URL }}
            VITE_WEB_DEV_0=${{ secrets.VITE_WEB_DEV_0 }}
            
          EOF

      - name: Check environment variable
        run: |
          echo "API URL: ${{ secrets.VITE_APP_API_URL }}"
          echo "WEB DEV: ${{ secret.VITE_WEB_DEV_0 }}"

      - name: Install dependencies on EC2
        run: |
          echo "${{ secrets.BEBTIMER_EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.BEBTIMER_EC2_HOST }} << 'EOF'
            cd /home/ubuntu/bebTimerFront
            npm install  # Zainstaluj zależności
          EOF

      - name: Build application on EC2
        run: |
          echo "${{ secrets.BEBTIMER_EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.BEBTIMER_EC2_HOST }} << 'EOF'
            cd /home/ubuntu/bebTimerFront
            npm run build  # Zbuduj aplikację
          EOF

      - name: Install serve globally on EC2
        run: |
          echo "${{ secrets.BEBTIMER_EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.BEBTIMER_EC2_HOST }} << 'EOF'
            sudo npm install -g serve  # Zainstaluj serve globalnie
          EOF

      - name: Create systemd service
        run: |
          echo "${{ secrets.BEBTIMER_EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.BEBTIMER_EC2_HOST }} << 'EOF'
        
          # Utwórz plik systemd dla usługi
          sudo bash -c 'cat <<EOL > /etc/systemd/system/bebtimer.service
          [Unit]
          Description=BebTimer Application
          After=network.target

          [Service]
          User=ubuntu
          Group=ubuntu
          WorkingDirectory=/home/ubuntu/bebTimerFront/dist
          ExecStart=/usr/bin/serve -s /home/ubuntu/bebTimerFront/dist
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOL'

          # Włącz i uruchom usługę
          sudo systemctl enable bebtimer.service
          sudo systemctl start bebtimer.service
          
          # Opcjonalnie, sprawdź status usługi
          sudo systemctl status bebtimer.service
          EOF
