name: Deploy bebTimer Front to AWS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BEBTIMER_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.BEBTIMER_EC2_SSH_KEY }}
          port: 22
          source: "dist/*"
          target: "/home/ubuntu/bebTimerFront"

      - name: Create systemd service
        run: |
          echo "[Unit]
          Description=BebTimer Application
          After=network.target

          [Service]
          ExecStart=/usr/bin/node /home/ubuntu/bebTimerFront/dist/server.js
          WorkingDirectory=/home/ubuntu/bebTimerFront/dist
          Restart=always
          User=ubuntu
          Environment=PATH=/usr/bin:/usr/local/bin
          Environment=NODE_ENV=production

          [Install]
          WantedBy=multi-user.target" | sudo tee /etc/systemd/system/bebtimer.service

      - name: Reload systemd
        run: sudo systemctl daemon-reload

      - name: Start service
        run: sudo systemctl start bebtimer.service

      - name: Enable service
        run: sudo systemctl enable bebtimer.service

      - name: Enable service
        run: sudo systemctl status bebtimer.service
